### ISSUE TITLE
TRACKING: Filsnap Updates

### ISSUE THREAD

**Issue by hugomrdias** [filecoin-project/filsnap#1]
# Tasks
## Developer tooling and experience improvements
  - [x] Move repo to some PL Org
  - [x] Create a new npm package with PL bot 
  - [x] Setup CI to publish with PL bot
  - [x] Change repo tooling to something more up to date and canonical for easier development and contributions
  - [x] Make sure all npm scripts and local dev is fully functional, documented and easy to use.
  - [x] Update dependencies specially from metamask and filecoin.
  - [x] Move tests from https://github.com/hugomrdias/filsnap-testing to the filsnap repo
  - [x] Move CI from https://github.com/hugomrdias/filsnap-testing to the filsnap repo
  - [x] Added notice about repo the new repo on https://github.com/ChainSafe/filsnap

## Code Improvements

- [x] Zod schemas with validations and types for RPC messages and metamask state
- [x] RPC client for lotus using zod schemas 
- [x] `onRpcRequest` should check if `fil_configure` was called already and build up a "context" for other methods with snap, config, api client, keypair etc avoiding multiple instances and async tasks to get snap state.
- [x] Remove dependency on `@zondax/filecoin-signing-tools` and `Buffer`
- [x] Swap all the validation in `src/utils/params.ts` for zod schemas
- [x] Check new snaps UI https://docs.metamask.io/snaps/reference/rpc-api/#snap_dialog and `src/util/confirmation.ts`
- [x] Add pnpm patch to snaps-cli/dist/utils/misc.js changing config file to snap.config.cjs
- [x] Write new RPC or use some other client like izari-filecoin
- [x] compress snap bundle https://github.com/terser/terser
- [x] flask now forces semver in the snap version option change `metamask-testing-tools` to account for that
- [x] tests need to have the snap version injected from the snap manifest
- [x] export private key MM popup needs rework
- [x] sign raw popup rework
- [x] send message popup rework

## Metamask 10.28+ compatibility
  - [x] Research metamask new flask/snap permissions system (caveats based) and plan changes needed in filsnap.
  - [x] Update filsnap to the new permissions system
  - [x] Document changes and how it works to make future changes easier. (metamask said it may change again multiples until 10.29.0/end of the year)
  - [x] Unit and e2e tests for these changes.
  - [x] Check snap config type and check if we need to refactor it and where all the properties are used. 
  - [x] Make sure the snap manifest gets updated and committed in the CI 

## Filsnap adapter

- [x] Merge #6 
- [x] Make sure there are no breaking changes to the adapter API
- [x] Rework the demo
- [x] Publish demo
- [x] Check filsnap icons for the install snap popup
- [x] Publish new package to npm
- [x] e2e tests running against the demo app
- [x] Fix selection highlight in the demo app
- [x] deploy with npm:filsnap SNAP_ID

## Support FEVM transactions
  - [x] Research FVM/FEVM transactions, requirements, flows and tools.
  - [x] Support send FIL to f410 addrs 
  - [x] Handle FEVM transactions (cbor encoded) 
  - [x] New unit and e2e tests for FEVM features 
  - [x] Update demo page with FEVM features
  - [x] Collaborate with Glif to validate filsnap works as expected

## Others

- [x] Write up about moving aways from zondax dependencies 
- [x] Improve packages readme and add a few examples
- [x] Improve js docs descriptions 
- [x] #35 (not possible)
- [x] #36
- [x] #37
- [x] #38

# References
- https://github.com/ChainSafe/dappeteer#usage-with-snaps
- https://github.com/MetaMask/snaps-monorepo
- https://www.npmjs.com/package/@metamask/snaps-cli
- https://docs.metamask.io/guide/snaps.html
- https://github.com/ChainSafe/filsnap
- Original issue https://github.com/ChainSafe/filsnap/issues/132
- https://hyperspace.yoga/#faucet
- https://faucet.calibration.fildev.network/
- https://github.com/Zondax/izari-filecoin
- https://github.com/glifio/modules

# Notes
- Glif RPC nodes docs https://api.node.glif.io/
