### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by hugomrdias** [filecoin-project/filsnap#202]
```[tasklist]
### Tasks
- [ ] #189
- [ ] #190
- [ ] https://github.com/filecoin-project/filsnap/issues/188
- [ ] https://github.com/filecoin-project/filsnap/issues/187
- [ ] https://github.com/filecoin-project/filsnap/issues/167
- [ ] https://github.com/filecoin-project/filsnap/issues/137
- [ ] https://github.com/filecoin-project/filsnap/issues/178
- [ ] https://github.com/filecoin-project/filsnap/issues/209
```
